name: "macOS CPU CI Pipeline"

on:
  push:
    branches: [fs-eire/mac-ci-pipeline-refactor, "rel-*"]
  pull_request:
    branches: [fs-eire/mac-ci-pipeline-refactor]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/macos-ci-workflow.yml
