name: "macOS XNNPACK CI Pipeline"

on:
  push:
    branches: [main, "rel-*"]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  x86_64-Xcode14:
    runs-on: macos-13
    env:
      MACOSX_DEPLOYMENT_TARGET: "13.3"
      python_version: "3.11"
    strategy:
      matrix:
        build_config: ["Debug", "Release"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: macOS CI pipeline shared steps
        uses: ./macos_shared_prepare_steps.yml
        with:
          platform_machine: "amd64"
          python_version: ${{ env.python_version }}
          xcode_version: "14.3.1"
          use_cache: true

      - name: Build and Test on macOS
        run: |
          python ./tools/ci_build/build.py \
            --build_dir ./build \
            --skip_submodule_sync \
            --cmake_generator=Ninja \
            --parallel \
            --use_vcpkg --use_vcpkg_ms_internal_asset_cache --use_binskim_compliant_compile_flags \
            --build_shared_lib \
            --use_xnnpack \
            --build_nodejs \
            --build_objc \
            --build_wheel \
            --build_java \
            --config ${{ matrix.build_config }}

  ARM64-Xcode16:
    runs-on: macos-15
    env:
      python_version: "3.11"
    strategy:
      matrix:
        build_config: ["Debug", "Release"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Call Common Steps
        uses: ./macos_shared_prepare_steps.yml
        with:
          platform_machine: "arm64"
          python_version: ${{ env.python_version }}
          xcode_version: "16"
          use_cache: true

      - name: Build and test
        shell: bash
        run: |
          python ./tools/ci_build/build.py \
            --build_dir ./build \
            --skip_submodule_sync \
            --cmake_generator=Ninja \
            --parallel \
            --use_vcpkg --use_vcpkg_ms_internal_asset_cache --use_binskim_compliant_compile_flags \
            --build_shared_lib \
            --use_xnnpack \
            --build_nodejs \
            --build_objc \
            --build_wheel \
            --build_java \
            --config ${{ matrix.build_config }}
